Message-ID: <1826031a-cca3-47db-90c4-bc656f3a1d1f>
Date: Wed, 29 Nov 2023 22:43:44 +0700
MIME-Version: 1.0
User-Agent: 
Content-Language: en-US
From: example@localhost
To: pttien@fit.hcmus.edu.vn
Cc: example@localhost
Subject: Test Email

This is a multi-part message in MIME format.
--------------95ad3b6262a740c48c6369385a16f2e9
Content-Type: text/plain; charset=UTF-8; format=flowed
Content-Transfer-Encoding: 7bit

This is a test email

--------------95ad3b6262a740c48c6369385a16f2e9
Content-Type: application/octet-stream; charset=UTF-8; name="test.cpp"
Content-Disposition: attachment; filename="test.cpp"
Content-Transfer-Encoding: base64

Y3BwIHRlc3Q=
--------------95ad3b6262a740c48c6369385a16f2e9
Content-Type: text/plain; charset=UTF-8; name="test.txt"
Content-Disposition: attachment; filename="test.txt"
Content-Transfer-Encoding: base64


--------------95ad3b6262a740c48c6369385a16f2e9--

