Message-ID: <b095f395-61a3-4271-8795-5d3f22d671f0>
Date: Fri, 15 Dec 2023 01:38:57 +0700
MIME-Version: 1.0
User-Agent: 
Content-Language: en-US
From: example@localhost
To: pttien@fit.hcmus.edu.vn
Cc: example@localhost
Subject: Test Email w/ attachments
Content-Type: text/plain; charset=UTF-8; format=flowed
Content-Transfer-Encoding: 7bit

This is a test email with long content...This is a test email with long cont
ent...This is a test email with long content...This is a test email with lon
g content...This is a test email with long content...This is a test email wi
th long content...This is a test email with long content...This is a test em
ail with long content...

