Content-Type: multipart/mixed; boundary="------------590a9306239a49c7ad86c879e70197f8"
Message-ID: <1cfd4d17-7c79-4a24-bdce-51e5659ccbab>
Date: Sun, 10 Dec 2023 20:40:44 +0700
MIME-Version: 1.0
User-Agent: 
Content-Language: en-US
From: example@localhost
To: pttien@fit.hcmus.edu.vn
Cc: example@localhost
Subject: Test Email w/ attachments

This is a multi-part message in MIME format.
--------------590a9306239a49c7ad86c879e70197f8
Content-Type: text/plain; charset=UTF-8; format=flowed
Content-Transfer-Encoding: 7bit

This is a test email with long content...This is a test email with long cont
ent...This is a test email with long content...This is a test email with lon
g content...This is a test email with long content...This is a test email wi
th long content...This is a test email with long content...This is a test em
ail with long content...

--------------590a9306239a49c7ad86c879e70197f8
Content-Type: application/octet-stream; charset=UTF-8; name="test.cpp"
Content-Disposition: attachment; filename="test.cpp"
Content-Transfer-Encoding: base64

Y3BwIHRlc3Q=
--------------590a9306239a49c7ad86c879e70197f8
Content-Type: text/plain; charset=UTF-8; name="test.txt"
Content-Disposition: attachment; filename="test.txt"
Content-Transfer-Encoding: base64

SGVsbG8gd29ybGQ=
--------------590a9306239a49c7ad86c879e70197f8--

