Content-Type: multipart/mixed; boundary="------------fbf3d8b1a7e741f3a10d412885112d1e"
Message-ID: <407b27f9-d0f1-4087-892e-de0853777871>
Date: Sun, 10 Dec 2023 20:41:56 +0700
MIME-Version: 1.0
User-Agent: 
Content-Language: en-US
From: example@localhost
To: pttien@fit.hcmus.edu.vn
Cc: example@localhost
Subject: Test Email w/ attachments

This is a multi-part message in MIME format.
--------------fbf3d8b1a7e741f3a10d412885112d1e
Content-Type: text/plain; charset=UTF-8; format=flowed
Content-Transfer-Encoding: 7bit

This is a test email with long content...This is a test email with long cont
ent...This is a test email with long content...This is a test email with lon
g content...This is a test email with long content...This is a test email wi
th long content...This is a test email with long content...This is a test em
ail with long content...

--------------fbf3d8b1a7e741f3a10d412885112d1e
Content-Type: application/octet-stream; charset=UTF-8; name="test.cpp"
Content-Disposition: attachment; filename="test.cpp"
Content-Transfer-Encoding: base64

Y3BwIHRlc3Q=
--------------fbf3d8b1a7e741f3a10d412885112d1e
Content-Type: text/plain; charset=UTF-8; name="test.txt"
Content-Disposition: attachment; filename="test.txt"
Content-Transfer-Encoding: base64

SGVsbG8gd29ybGQ=
--------------fbf3d8b1a7e741f3a10d412885112d1e--

