Message-ID: <0d96e063-8842-4819-870e-fa1131319be3>
Date: Thu, 14 Dec 2023 21:57:15 +0700
MIME-Version: 1.0
User-Agent: 
Content-Language: en-US
From: example@localhost
To: pttien@fit.hcmus.edu.vn
Cc: example@localhost
Subject: Test Email w/ attachments
Content-Type: text/plain; charset=UTF-8; format=flowed
Content-Transfer-Encoding: 7bit

This is a test email with long content...This is a test email with long cont
ent...This is a test email with long content...This is a test email with lon
g content...This is a test email with long content...This is a test email wi
th long content...This is a test email with long content...This is a test em
ail with long content...

