Content-Type: multipart/mixed; boundary="------------32dad99284e04931b6fd17697f2c2f61"
Message-ID: <0a11be84-5c63-41be-a9ba-f14cc226ab4c>
Date: Thu, 30 Nov 2023 06:23:03 +0700
MIME-Version: 1.0
User-Agent: 
Content-Language: en-US
From: example@localhost
To: pttien@fit.hcmus.edu.vn
Cc: example@localhost
Subject: Test Email

This is a multi-part message in MIME format.
--------------32dad99284e04931b6fd17697f2c2f61
Content-Type: text/plain; charset=UTF-8; format=flowed
Content-Transfer-Encoding: 7bit

This is a test email

--------------32dad99284e04931b6fd17697f2c2f61
Content-Type: application/octet-stream; charset=UTF-8; name="test.cpp"
Content-Disposition: attachment; filename="test.cpp"
Content-Transfer-Encoding: base64

Y3BwIHRlc3Q=
--------------32dad99284e04931b6fd17697f2c2f61
Content-Type: text/plain; charset=UTF-8; name="test.txt"
Content-Disposition: attachment; filename="test.txt"
Content-Transfer-Encoding: base64


--------------32dad99284e04931b6fd17697f2c2f61--

